version: "3"
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server:rw
    environment:
      FLASK_ENV: development
  app:
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app:rw
