version: '3'
services:
  # server:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - '.:/Back'
  #   environment:
  #     FLASK_ENV: development
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - '.:/front'
      - '/front/node_modules'