version: '3'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - '.:/server'
    environment:
      FLASK_ENV: development
  app:
    build: ./app
    ports:
      - "8080:8080"
    volumes:
      - '/app/node_modules'
      - './app:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true