version: '3'
services:
  server:
    build: ./server
    command: flask run
    ports:
      - "5000:5000"
    volumes:
      - './server/:/server/'
    environment:
      FLASK_ENV: development
  app:
    build: ./app
    command: yarn serve
    ports:
      - "8080:8080"
    volumes:
      - './app/:/app/'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true